bossNameIndex = {
	["Attumen the Huntsman"] = 3,
	["Tenris Mirkblood"] = 3,
	["Moroes"] = 3,
	["Maiden of Virtue"] = 3,
	["The Opera Event"] = 3,
	["The Curator"] = 3,
	["Terestian Illhoof"] = 4,
	["Shade of Aran"] = 4,
	["Netherspite"] = 4,
	["The Chess Event"] = 4,
	["Prince Malchezaar"] = 5,
	["Nightbane"] = 5,
	
	["Magtheridon"] = 5,
	
	["High King Maulgar"] = 4,
	["Gruul the Dragonkiller"] = 5,
	
	["Hydross the Unstable"] = 4,
	["The Lurker Below"] = 4,
	["Leotheras the Blind"] = 4,
	["Fathom-Lord Karathress"] = 6,
	["Morogrim Tidewalker"] = 6,
	["Lady Vashj"] = 8,
	
	["Al'ar"] = 7,
	["Void Reaver"] = 7,
	["High Astromancer Solarian"] = 7,
	["Kael'thas Sunstrider"] = 10,
	
	["Rage Winterchill"] = 8,
	["Anetheron"] = 8,
	["Kaz'rogal"] = 9,
	["Azgalor"] = 9,
	["Archimonde"] = 11,
	
	["High Warlord Naj'entus"] = 10,
	["Supremus"] = 10,
	["Shade of Akama"] = 10,
	["Teron Gorefiend"] = 10,
	["Gurtogg Bloodboil"] = 11,
	["Reliquary of Souls"] = 11,
	["Mother Shahraz"] = 12,
	["Illidari Council"] = 12,
	["Illidan Stormrage"] = 15,
	
	["Kalecgos"] = 12,
	["Brutallus"] = 13,
	["Felmyst"] = 13,
	["The Eredar Twins"] = 14,
	["M'uru"] = 14,
	["Kil'jaeden"] = 18
}

tokenItemLevels = {
	-- Tier 6
	["Belt of the Forgotten Conqueror"] = 154,
	["Belt of the Forgotten Protector"] = 154,
	["Belt of the Forgotten Vanquisher"] = 154,
	["Boots of the Forgotten Conqueror"] = 154,
	["Boots of the Forgotten Protector"] = 154,
	["Boots of the Forgotten Vanquisher"] = 154,
	["Bracers of the Forgotten Conqueror"] = 154,
	["Bracers of the Forgotten Protector"] = 154,
	["Bracers of the Forgotten Vanquisher"] = 154,
	["Chestguard of the Forgotten Conqueror"] = 146,
	["Chestguard of the Forgotten Protector"] = 146,
	["Chestguard of the Forgotten Vanquisher"] = 146,
	["Gloves of the Forgotten Conqueror"] = 146,
	["Gloves of the Forgotten Protector"] = 146,
	["Gloves of the Forgotten Vanquisher"] = 146,
	["Helm of the Forgotten Conqueror"] = 146,
	["Helm of the Forgotten Protector"] = 146,
	["Helm of the Forgotten Vanquisher"] = 146,
	["Leggings of the Forgotten Conqueror"] = 146,
	["Leggings of the Forgotten Protector"] = 146,
	["Leggings of the Forgotten Vanquisher"] = 146,
	["Pauldrons of the Forgotten Conqueror"] = 146,
	["Pauldrons of the Forgotten Protector"] = 146,
	["Pauldrons of the Forgotten Vanquisher"] = 146,
	
	-- Tier 5
	["Chestguard of the Vanquished Champion"] = 133,
	["Chestguard of the Vanquished Defender"] = 133,
	["Chestguard of the Vanquished Hero"] = 133,
	["Gloves of the Vanquished Champion"] = 133,
	["Gloves of the Vanquished Defender"] = 133,
	["Gloves of the Vanquished Hero"] = 133,
	["Helm of the Vanquished Champion"] = 133,
	["Helm of the Vanquished Defender"] = 133,
	["Helm of the Vanquished Hero"] = 133,
	["Leggings of the Vanquished Champion"] = 133,
	["Leggings of the Vanquished Defender"] = 133,
	["Leggings of the Vanquished Hero"] = 133,
	["Pauldrons of the Vanquished Champion"] = 133,
	["Pauldrons of the Vanquished Defender"] = 133,
	["Pauldrons of the Vanquished Hero"] = 133,
	
	-- Tier 4
	["Chestguard of the Fallen Champion"] = 120,
	["Chestguard of the Fallen Defender"] = 120,
	["Chestguard of the Fallen Hero"] = 120,
	["Gloves of the Fallen Champion"] = 120,
	["Gloves of the Fallen Defender"] = 120,
	["Gloves of the Fallen Hero"] = 120,
	["Helm of the Fallen Champion"] = 120,
	["Helm of the Fallen Defender"] = 120,
	["Helm of the Fallen Hero"] = 120,
	["Leggings of the Fallen Champion"] = 120,
	["Leggings of the Fallen Defender"] = 120,
	["Leggings of the Fallen Hero"] = 120,
	["Pauldrons of the Fallen Champion"] = 120,
	["Pauldrons of the Fallen Defender"] = 120,
	["Pauldrons of the Fallen Hero"] = 120
}

-- Items to be ignored when considering automatically opening the distribution window
itemExceptions = {"Netherstrand Longbow", "Staff of Disintegration", "Warp Slicer", "Phaseshift Bulwark", "Cosmic Infuser", "Infinity Blades", "Devastation", "Nether Spike"}